### ISSUE TITLE
V2 Design Proposal

### ISSUE THREAD

**Issue by gvauter** [RedHatProductSecurity/oscal-automation-libs#23]
# V2 Design Proposal

**Authors**: [gvauter@redhat.com](mailto:gvauter@redhat.com), [jpower@redhat.com](mailto:jpower@redhat.com)

**Begin Design Discussion**: 2024-07-25

**Status:** `draft`

## Summary/Abstract

This design outlines a series of updates to the repository to move away from the original Makefile/Bash content towards a Python SDK. The initial codebase of the SDK will be extracted from the existing [trestle-bot](https://github.com/RedHatProductSecurity/trestle-bot) project to serve as a core library for building OSCAL automation tooling.

### Motivation and problem space

A Python based SDK is being favored over the existing content.  The existing [trestle-bot](https://github.com/RedHatProductSecurity/trestle-bot) repo contains core Python logic that is not specific to its implementation and would serve as a good core library for other projects.

### Impact and desired outcome

Existing content would remain available under a `v1` repo tag.  This repo would be repurposed to contain a Python SDK.  All future features and enhancements would be included in the new Python SDK.

## Goals

The primary goal is to develop a Python SDK that can be leveraged for OSCAL automation.

## Proposal

This repository would be repurposed to provide a Python SDK for building OSCAL automation tooling.  The SDK will be made available as a Python package for installation via the `pypi` registry.  The existing content would be moved under a top level directory that would not be packaged with the Python libraries. 

## Design Details

* setup project to use Poetry for dependency management and package publishing
* move the following directories into a `/v1` directory
	* `iac`
	* `mk`
	* `scripts`
	* `templates`
* create a new `oscal_automation_libs` top level directory for Python source code
* migrate the following directories from trestle-bot
	* `tasks`
	* `transformers`
	* `const.py` # all relevant content

### Update/Rollback Compatibility

Users will need to reference existing automation via the v1 tag.  Users may also choose to clone the repo using the commit hash `332991ba2b0597dfb2115d626bb45d38dc30bcb8` to continue using the existing repo content.

**Comment by gvauter** [comment]
@jpower432 @d10n After further review, it seems a more straightforward approach will be to leverage the [trestle-bot](https://github.com/RedHatProductSecurity/trestle-bot) repository as a "monorepo" for the core SDK and the trestle-bot implementation.  This repo could then be archived.

**Comment by jpower432** [comment]
Thanks @gvauter. I agree. We should create an issue to add a link in the README to `trestle-bot` as our updated automation tool and archive this repository.

**Comment by gvauter** [comment]
> Thanks @gvauter. I agree. We should create an issue to add a link in the README to `trestle-bot` as our updated automation tool and archive this repository.

Issue #24 created for the README update and archive tasks.  I'll close this issue.
